### ISSUE TITLE
Upload fails, no file found

### ISSUE THREAD

**Issue by ovidiuvisan** [jpg0/eyego#2]
~/eyego/eyego$ go run main.go 
2013/09/19 00:15:47 Server starting...
2013/09/19 00:15:52 Upload started...
2013/09/19 00:16:02 Upload started...
2013/09/19 00:16:04 Uploading 101_0106.JPG.tar
2013/09/19 00:16:04 http: panic serving 192.168.1.7:42840: open : no such file or directory
goroutine 4 [running]:
net/http.func·007()
	/usr/lib/go/src/pkg/net/http/server.go:1022 +0xac
github.com/jpg0/eyego.geotag(0xc2000fe100, 0x17, 0x0, 0x0, 0xc2000fe10b, ...)
	/usr/lib/go/site/src/github.com/jpg0/eyego/geotag.go:12 +0xb1
github.com/jpg0/eyego.processUpload(0xc2000fe100, 0x17, 0x0, 0x0, 0xc200000558, ...)
	/usr/lib/go/site/src/github.com/jpg0/eyego/receiver.go:75 +0x8e
github.com/jpg0/eyego.doPhotoUpload(0xc2000aab60, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/site/src/github.com/jpg0/eyego/receiver.go:71 +0x44d
github.com/jpg0/eyego.Handler(0xc2000a2e40, 0xc2000ff230, 0xc2000aab60)
	/usr/lib/go/site/src/github.com/jpg0/eyego/server.go:40 +0x654
net/http.HandlerFunc.ServeHTTP(0x6d2fe8, 0xc2000a2e40, 0xc2000ff230, 0xc2000aab60)
	/usr/lib/go/src/pkg/net/http/server.go:1149 +0x3e
net/http.(*ServeMux).ServeHTTP(0xc2000a94e0, 0xc2000a2e40, 0xc2000ff230, 0xc2000aab60)
	/usr/lib/go/src/pkg/net/http/server.go:1416 +0x11d
net/http.serverHandler.ServeHTTP(0xc2000a6550, 0xc2000a2e40, 0xc2000ff230, 0xc2000aab60)
	/usr/lib/go/src/pkg/net/http/server.go:1517 +0x16c
net/http.(*conn).serve(0xc2000d32d0)
	/usr/lib/go/src/pkg/net/http/server.go:1096 +0x765
created by net/http.(*Server).Serve
	/usr/lib/go/src/pkg/net/http/server.go:1564 +0x266
^Cexit status 2

**Comment by jpg0** [comment]
I'm closing this as obsolete
